Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
  0%|                                                                                                                                                          | 0/3 [00:00<?, ?batch/s]
  0%|                                                                                                                                                       | 0/3782 [00:00<?, ?batch/s]
resume /home/jmw/ing/myfi/vfi/ckpt
load a checkpoint at/home/jmw/ing/myfi/vfi/ckptfor/home/jmw/ing/myfi/vfi/ckpt/ckpt-0
  0%|                                                                                                                                                          | 0/3 [00:07<?, ?batch/s]
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 8.47s
I1121 16:55:17.671578 139767974977920 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 8.47s
[  FAILED  ] ModelsTest.test_train_eval
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
W1121 16:55:17.722650 139767974977920 checkpoint.py:204] Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.iter
W1121 16:55:17.722974 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_1
W1121 16:55:17.723207 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_2
W1121 16:55:17.723387 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.decay
W1121 16:55:17.723544 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.0
W1121 16:55:17.723728 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.0
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.1
W1121 16:55:17.723907 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.2
W1121 16:55:17.724056 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.3
W1121 16:55:17.724186 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.3
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.4
W1121 16:55:17.724311 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.4
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.5
W1121 16:55:17.724405 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.5
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.6
W1121 16:55:17.724499 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.6
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.7
W1121 16:55:17.724593 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.7
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.8
W1121 16:55:17.724729 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.8
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.9
W1121 16:55:17.724860 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.9
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.10
W1121 16:55:17.724953 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.10
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.11
W1121 16:55:17.725047 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.11
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.12
W1121 16:55:17.725159 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.12
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.13
W1121 16:55:17.725255 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.13
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.14
W1121 16:55:17.725399 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.14
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.15
W1121 16:55:17.725530 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.15
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.16
W1121 16:55:17.725624 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.16
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.17
W1121 16:55:17.725735 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.17
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.18
W1121 16:55:17.725843 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.18
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.19
W1121 16:55:17.725937 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.19
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.20
W1121 16:55:17.726031 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.20
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.21
W1121 16:55:17.726124 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.21
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.22
W1121 16:55:17.726218 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.22
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.23
W1121 16:55:17.726330 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.23
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.24
W1121 16:55:17.726423 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.24
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.25
W1121 16:55:17.726515 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.25
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.26
W1121 16:55:17.726607 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.26
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.27
W1121 16:55:17.726700 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.27
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.28
W1121 16:55:17.726792 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.28
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.29
W1121 16:55:17.726884 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.29
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.30
W1121 16:55:17.726977 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.30
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.31
W1121 16:55:17.727069 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.31
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.32
W1121 16:55:17.727161 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.32
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.33
W1121 16:55:17.727253 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.33
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.34
W1121 16:55:17.727346 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.34
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.35
W1121 16:55:17.727455 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.35
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.36
W1121 16:55:17.727549 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.36
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.37
W1121 16:55:17.727642 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.37
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.38
W1121 16:55:17.727735 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.38
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.39
W1121 16:55:17.727828 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.39
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.40
W1121 16:55:17.727921 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.40
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.41
W1121 16:55:17.728015 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.41
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.42
W1121 16:55:17.728108 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.42
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.43
W1121 16:55:17.728201 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.43
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.44
W1121 16:55:17.728294 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.44
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.45
W1121 16:55:17.728387 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.45
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.46
W1121 16:55:17.728481 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.46
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.47
W1121 16:55:17.728574 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.47
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.48
W1121 16:55:17.728667 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.48
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.49
W1121 16:55:17.728759 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.49
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.50
W1121 16:55:17.728881 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.50
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.51
W1121 16:55:17.728989 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.51
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.52
W1121 16:55:17.729116 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.52
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.53
W1121 16:55:17.729209 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.53
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.54
W1121 16:55:17.729302 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.54
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.55
W1121 16:55:17.729396 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.55
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.56
W1121 16:55:17.729489 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.56
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.57
W1121 16:55:17.729582 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.57
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.58
W1121 16:55:17.729675 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.58
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.59
W1121 16:55:17.729768 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.59
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.60
W1121 16:55:17.729861 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.60
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.61
W1121 16:55:17.729954 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.61
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.62
W1121 16:55:17.730047 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.62
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.63
W1121 16:55:17.730140 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.63
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.64
W1121 16:55:17.730233 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.64
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.65
W1121 16:55:17.730331 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.65
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.66
W1121 16:55:17.730457 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.66
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.67
W1121 16:55:17.730581 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.67
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.68
W1121 16:55:17.730705 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.68
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.69
W1121 16:55:17.730828 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.69
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.70
W1121 16:55:17.730920 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.70
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.71
W1121 16:55:17.731014 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.71
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.72
W1121 16:55:17.731106 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.72
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.73
W1121 16:55:17.731199 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.73
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.74
W1121 16:55:17.731292 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.74
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.75
W1121 16:55:17.731384 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.75
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.76
W1121 16:55:17.731476 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.76
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.77
W1121 16:55:17.731570 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.77
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.78
W1121 16:55:17.731662 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.78
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.79
W1121 16:55:17.731755 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.79
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.80
W1121 16:55:17.731849 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.80
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.81
W1121 16:55:17.731941 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.81
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.82
W1121 16:55:17.732035 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.82
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.83
W1121 16:55:17.732127 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.83
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.84
W1121 16:55:17.732221 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.84
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.85
W1121 16:55:17.732314 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.85
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.86
W1121 16:55:17.732406 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.86
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.87
W1121 16:55:17.732499 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.87
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.88
W1121 16:55:17.732591 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.88
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.89
W1121 16:55:17.732685 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.89
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.90
W1121 16:55:17.732778 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.90
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.91
W1121 16:55:17.732870 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.91
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.92
W1121 16:55:17.732966 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.92
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.93
W1121 16:55:17.733060 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.93
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.94
W1121 16:55:17.733153 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.94
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.95
W1121 16:55:17.733246 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.95
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.96
W1121 16:55:17.733339 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.96
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.97
W1121 16:55:17.733455 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.97
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.98
W1121 16:55:17.733553 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.98
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.99
W1121 16:55:17.733648 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.99
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.100
W1121 16:55:17.733743 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.100
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.101
W1121 16:55:17.733840 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.101
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.102
W1121 16:55:17.733936 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.102
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.103
W1121 16:55:17.734031 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.103
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.104
W1121 16:55:17.734126 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.104
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.105
W1121 16:55:17.734222 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.105
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.106
W1121 16:55:17.734323 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.106
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.107
W1121 16:55:17.734418 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.107
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.108
W1121 16:55:17.734514 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.108
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.109
W1121 16:55:17.734609 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.109
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.110
W1121 16:55:17.734704 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.110
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.111
W1121 16:55:17.734800 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.111
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.112
W1121 16:55:17.734895 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.112
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.113
W1121 16:55:17.734990 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.113
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.114
W1121 16:55:17.735084 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.114
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.115
W1121 16:55:17.735179 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.115
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.116
W1121 16:55:17.735273 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.116
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.117
W1121 16:55:17.735368 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.117
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.118
W1121 16:55:17.735464 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.118
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.119
W1121 16:55:17.735558 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.119
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.120
W1121 16:55:17.735652 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.120
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.121
W1121 16:55:17.735746 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.121
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.122
W1121 16:55:17.735840 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.122
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.123
W1121 16:55:17.735935 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.123
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.124
W1121 16:55:17.736029 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.124
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.125
W1121 16:55:17.736123 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.125
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.126
W1121 16:55:17.736218 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.126
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.127
W1121 16:55:17.736312 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.127
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.128
W1121 16:55:17.736406 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.128
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.129
W1121 16:55:17.736500 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.129
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.130
W1121 16:55:17.736595 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.131
W1121 16:55:17.736690 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.132
W1121 16:55:17.736784 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.133
W1121 16:55:17.736879 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.134
W1121 16:55:17.736973 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.135
W1121 16:55:17.737067 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.136
W1121 16:55:17.737161 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.137
W1121 16:55:17.737255 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.138
W1121 16:55:17.737350 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.139
W1121 16:55:17.737444 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.140
W1121 16:55:17.737538 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.141
W1121 16:55:17.737632 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.142
W1121 16:55:17.737727 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.143
W1121 16:55:17.737822 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.144
W1121 16:55:17.737917 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.145
W1121 16:55:17.738012 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.146
W1121 16:55:17.738107 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.147
W1121 16:55:17.738231 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.148
W1121 16:55:17.738339 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.149
W1121 16:55:17.738436 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.150
W1121 16:55:17.738531 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.151
W1121 16:55:17.738626 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.152
W1121 16:55:17.738721 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.153
W1121 16:55:17.738816 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.154
W1121 16:55:17.738911 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.155
W1121 16:55:17.739006 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.156
W1121 16:55:17.739101 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.157
W1121 16:55:17.739195 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.158
W1121 16:55:17.739290 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.159
W1121 16:55:17.739386 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.160
W1121 16:55:17.739480 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.161
W1121 16:55:17.739575 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.162
W1121 16:55:17.739669 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.163
W1121 16:55:17.739764 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.164
W1121 16:55:17.739859 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.165
W1121 16:55:17.739954 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.166
W1121 16:55:17.740048 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.167
W1121 16:55:17.740143 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.168
W1121 16:55:17.740237 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.169
W1121 16:55:17.740331 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.170
W1121 16:55:17.740426 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.171
W1121 16:55:17.740520 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.172
W1121 16:55:17.740614 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.173
W1121 16:55:17.740708 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.174
W1121 16:55:17.740802 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.175
W1121 16:55:17.740897 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.176
W1121 16:55:17.740991 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.177
W1121 16:55:17.741085 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.178
W1121 16:55:17.741180 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.179
W1121 16:55:17.741274 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.180
W1121 16:55:17.741369 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.181
W1121 16:55:17.741466 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.182
W1121 16:55:17.741562 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.183
W1121 16:55:17.741657 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.184
W1121 16:55:17.741751 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.185
W1121 16:55:17.741846 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.185
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.0
W1121 16:55:17.741941 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.0
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.1
W1121 16:55:17.742037 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.2
W1121 16:55:17.742131 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.3
W1121 16:55:17.742226 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.3
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.4
W1121 16:55:17.742327 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.4
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.5
W1121 16:55:17.742422 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.5
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.6
W1121 16:55:17.742517 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.6
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.7
W1121 16:55:17.742612 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.7
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.8
W1121 16:55:17.742707 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.8
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.9
W1121 16:55:17.742802 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.9
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.10
W1121 16:55:17.742897 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.10
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.11
W1121 16:55:17.742992 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.11
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.12
W1121 16:55:17.743087 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.12
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.13
W1121 16:55:17.743183 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.13
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.14
W1121 16:55:17.743278 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.14
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.15
W1121 16:55:17.743374 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.15
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.16
W1121 16:55:17.743470 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.16
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.17
W1121 16:55:17.743564 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.17
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.18
W1121 16:55:17.743659 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.18
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.19
W1121 16:55:17.743753 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.19
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.20
W1121 16:55:17.743848 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.20
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.21
W1121 16:55:17.743941 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.21
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.22
W1121 16:55:17.744036 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.22
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.23
W1121 16:55:17.744132 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.23
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.24
W1121 16:55:17.744227 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.24
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.25
W1121 16:55:17.744323 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.25
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.26
W1121 16:55:17.744419 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.26
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.27
W1121 16:55:17.744514 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.27
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.28
W1121 16:55:17.744609 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.28
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.29
W1121 16:55:17.744703 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.29
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.30
W1121 16:55:17.744798 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.30
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.31
W1121 16:55:17.744893 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.31
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.32
W1121 16:55:17.744987 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.32
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.33
W1121 16:55:17.745083 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.33
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.34
W1121 16:55:17.745177 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.34
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.35
W1121 16:55:17.745273 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.35
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.36
W1121 16:55:17.745368 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.36
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.37
W1121 16:55:17.745462 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.37
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.38
W1121 16:55:17.745557 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.38
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.39
W1121 16:55:17.745652 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.39
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.40
W1121 16:55:17.745782 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.40
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.41
W1121 16:55:17.745877 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.41
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.42
W1121 16:55:17.745973 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.42
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.43
W1121 16:55:17.746076 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.43
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.44
W1121 16:55:17.746204 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.44
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.45
W1121 16:55:17.746305 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.45
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.46
W1121 16:55:17.746415 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.46
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.47
W1121 16:55:17.746529 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.47
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.48
W1121 16:55:17.746655 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.48
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.49
W1121 16:55:17.746749 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.49
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.50
W1121 16:55:17.746845 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.50
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.51
W1121 16:55:17.746942 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.51
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.52
W1121 16:55:17.747039 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.52
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.53
W1121 16:55:17.747134 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.53
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.54
W1121 16:55:17.747231 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.54
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.55
W1121 16:55:17.747327 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.55
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.56
W1121 16:55:17.747423 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.56
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.57
W1121 16:55:17.747521 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.57
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.58
W1121 16:55:17.747627 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.58
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.59
W1121 16:55:17.747731 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.59
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.60
W1121 16:55:17.747838 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.60
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.61
W1121 16:55:17.747944 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.61
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.62
W1121 16:55:17.748049 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.62
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.63
W1121 16:55:17.748155 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.63
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.64
W1121 16:55:17.748261 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.64
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.65
W1121 16:55:17.748367 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.65
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.66
W1121 16:55:17.748473 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.66
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.67
W1121 16:55:17.748578 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.67
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.68
W1121 16:55:17.748683 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.68
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.69
W1121 16:55:17.748789 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.69
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.70
W1121 16:55:17.748894 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.70
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.71
W1121 16:55:17.749000 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.71
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.72
W1121 16:55:17.749105 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.72
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.73
W1121 16:55:17.749210 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.73
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.74
W1121 16:55:17.749315 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.74
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.75
W1121 16:55:17.749422 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.75
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.76
W1121 16:55:17.749528 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.76
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.77
W1121 16:55:17.749634 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.77
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.78
W1121 16:55:17.749739 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.78
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.79
W1121 16:55:17.749844 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.79
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.80
W1121 16:55:17.749949 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.80
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.81
W1121 16:55:17.750055 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.81
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.82
W1121 16:55:17.750160 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.82
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.83
W1121 16:55:17.750268 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.83
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.84
W1121 16:55:17.750376 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.84
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.85
W1121 16:55:17.750481 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.85
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.86
W1121 16:55:17.750587 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.86
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.87
W1121 16:55:17.750688 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.87
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.88
W1121 16:55:17.750784 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.88
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.89
W1121 16:55:17.750880 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.89
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.90
W1121 16:55:17.750975 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.90
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.91
W1121 16:55:17.751070 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.91
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.92
W1121 16:55:17.751165 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.92
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.93
W1121 16:55:17.751260 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.93
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.94
W1121 16:55:17.751356 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.94
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.95
W1121 16:55:17.751451 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.95
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.96
W1121 16:55:17.751546 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.96
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.97
W1121 16:55:17.751640 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.97
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.98
W1121 16:55:17.751734 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.98
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.99
W1121 16:55:17.751829 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.99
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.100
W1121 16:55:17.751924 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.100
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.101
W1121 16:55:17.752019 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.101
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.102
W1121 16:55:17.752114 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.102
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.103
W1121 16:55:17.752210 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.103
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.104
W1121 16:55:17.752305 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.104
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.105
W1121 16:55:17.752400 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.105
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.106
W1121 16:55:17.752533 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.106
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.107
W1121 16:55:17.752633 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.107
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.108
W1121 16:55:17.752728 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.108
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.109
W1121 16:55:17.752823 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.109
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.110
W1121 16:55:17.752918 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.110
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.111
W1121 16:55:17.753014 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.111
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.112
W1121 16:55:17.753109 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.112
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.113
W1121 16:55:17.753205 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.113
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.114
W1121 16:55:17.753300 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.114
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.115
W1121 16:55:17.753395 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.115
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.116
W1121 16:55:17.753491 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.116
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.117
W1121 16:55:17.753587 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.117
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.118
W1121 16:55:17.753682 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.118
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.119
W1121 16:55:17.753777 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.119
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.120
W1121 16:55:17.753872 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.120
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.121
W1121 16:55:17.753967 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.121
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.122
W1121 16:55:17.754062 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.122
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.123
W1121 16:55:17.754157 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.123
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.124
W1121 16:55:17.754253 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.124
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.125
W1121 16:55:17.754355 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.125
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.126
W1121 16:55:17.754450 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.126
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.127
W1121 16:55:17.754544 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.127
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.128
W1121 16:55:17.754637 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.128
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.129
W1121 16:55:17.754731 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.129
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.130
W1121 16:55:17.754826 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.131
W1121 16:55:17.754920 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.132
W1121 16:55:17.755015 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.133
W1121 16:55:17.755109 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.134
W1121 16:55:17.755203 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.135
W1121 16:55:17.755298 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.136
W1121 16:55:17.755392 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.137
W1121 16:55:17.755487 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.138
W1121 16:55:17.755582 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.139
W1121 16:55:17.755677 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.140
W1121 16:55:17.755773 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.141
W1121 16:55:17.755868 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.142
W1121 16:55:17.755964 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.143
W1121 16:55:17.756058 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.144
W1121 16:55:17.756152 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.145
W1121 16:55:17.756246 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.146
W1121 16:55:17.756340 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.147
W1121 16:55:17.756434 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.148
W1121 16:55:17.756528 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.149
W1121 16:55:17.756622 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.150
W1121 16:55:17.756716 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.151
W1121 16:55:17.756811 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.152
W1121 16:55:17.756906 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.153
W1121 16:55:17.757002 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.154
W1121 16:55:17.757096 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.155
W1121 16:55:17.757205 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.156
W1121 16:55:17.757314 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.157
W1121 16:55:17.757421 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.158
W1121 16:55:17.757528 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.159
W1121 16:55:17.757636 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.160
W1121 16:55:17.757746 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.161
W1121 16:55:17.757854 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.162
W1121 16:55:17.757962 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.163
W1121 16:55:17.758074 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.164
W1121 16:55:17.758183 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.165
W1121 16:55:17.758295 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.166
W1121 16:55:17.758403 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.167
W1121 16:55:17.758501 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.168
W1121 16:55:17.758596 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.169
W1121 16:55:17.758702 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.170
W1121 16:55:17.758800 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.171
W1121 16:55:17.758895 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.172
W1121 16:55:17.758990 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.173
W1121 16:55:17.759084 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.174
W1121 16:55:17.759179 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.175
W1121 16:55:17.759275 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.176
W1121 16:55:17.759369 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.177
W1121 16:55:17.759465 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.178
W1121 16:55:17.759559 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.179
W1121 16:55:17.759653 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.180
W1121 16:55:17.759748 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.181
W1121 16:55:17.759843 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.182
W1121 16:55:17.759938 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.183
W1121 16:55:17.760033 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.184
W1121 16:55:17.760128 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.185
W1121 16:55:17.760222 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.185
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.0
W1121 16:55:17.760318 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.0
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.1
W1121 16:55:17.760414 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.2
W1121 16:55:17.760509 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.3
W1121 16:55:17.760603 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.3
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.4
W1121 16:55:17.760698 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.4
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.5
W1121 16:55:17.760792 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.5
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.6
W1121 16:55:17.760887 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.6
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.7
W1121 16:55:17.760982 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.7
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.8
W1121 16:55:17.761078 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.8
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.9
W1121 16:55:17.761173 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.9
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.10
W1121 16:55:17.761269 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.10
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.11
W1121 16:55:17.761363 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.11
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.12
W1121 16:55:17.761457 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.12
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.13
W1121 16:55:17.761552 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.13
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.14
W1121 16:55:17.761646 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.14
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.15
W1121 16:55:17.761741 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.15
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.16
W1121 16:55:17.761834 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.16
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.17
W1121 16:55:17.761929 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.17
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.18
W1121 16:55:17.762023 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.18
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.19
W1121 16:55:17.762118 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.19
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.20
W1121 16:55:17.762212 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.20
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.21
W1121 16:55:17.762310 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.21
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.22
W1121 16:55:17.762405 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.22
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.23
W1121 16:55:17.762499 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.23
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.24
W1121 16:55:17.762593 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.24
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.25
W1121 16:55:17.762688 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.25
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.26
W1121 16:55:17.762783 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.26
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.27
W1121 16:55:17.762877 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.27
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.28
W1121 16:55:17.762971 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.28
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.29
W1121 16:55:17.763065 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.29
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.30
W1121 16:55:17.763163 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.30
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.31
W1121 16:55:17.763290 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.31
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.32
W1121 16:55:17.763387 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.32
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.33
W1121 16:55:17.763481 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.33
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.34
W1121 16:55:17.763576 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.34
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.35
W1121 16:55:17.763671 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.35
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.36
W1121 16:55:17.763766 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.36
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.37
W1121 16:55:17.763861 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.37
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.38
W1121 16:55:17.763954 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.38
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.39
W1121 16:55:17.764049 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.39
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.40
W1121 16:55:17.764144 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.40
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.41
W1121 16:55:17.764239 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.41
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.42
W1121 16:55:17.764333 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.42
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.43
W1121 16:55:17.764428 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.43
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.44
W1121 16:55:17.764523 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.44
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.45
W1121 16:55:17.764617 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.45
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.46
W1121 16:55:17.764711 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.46
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.47
W1121 16:55:17.764805 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.47
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.48
W1121 16:55:17.764901 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.48
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.49
W1121 16:55:17.764995 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.49
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.50
W1121 16:55:17.765090 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.50
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.51
W1121 16:55:17.765185 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.51
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.52
W1121 16:55:17.765279 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.52
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.53
W1121 16:55:17.765374 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.53
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.54
W1121 16:55:17.765468 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.54
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.55
W1121 16:55:17.765562 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.55
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.56
W1121 16:55:17.765657 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.56
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.57
W1121 16:55:17.765752 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.57
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.58
W1121 16:55:17.765845 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.58
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.59
W1121 16:55:17.765938 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.59
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.60
W1121 16:55:17.766032 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.60
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.61
W1121 16:55:17.766127 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.61
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.62
W1121 16:55:17.766221 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.62
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.63
W1121 16:55:17.766320 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.63
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.64
W1121 16:55:17.766414 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.64
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.65
W1121 16:55:17.766508 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.65
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.66
W1121 16:55:17.766602 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.66
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.67
W1121 16:55:17.766696 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.67
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.68
W1121 16:55:17.766790 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.68
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.69
W1121 16:55:17.766885 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.69
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.70
W1121 16:55:17.766980 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.70
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.71
W1121 16:55:17.767073 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.71
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.72
W1121 16:55:17.767168 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.72
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.73
W1121 16:55:17.767263 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.73
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.74
W1121 16:55:17.767358 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.74
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.75
W1121 16:55:17.767452 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.75
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.76
W1121 16:55:17.767547 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.76
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.77
W1121 16:55:17.767642 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.77
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.78
W1121 16:55:17.767737 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.78
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.79
W1121 16:55:17.767831 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.79
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.80
W1121 16:55:17.767925 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.80
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.81
W1121 16:55:17.768019 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.81
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.82
W1121 16:55:17.768113 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.82
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.83
W1121 16:55:17.768207 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.83
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.84
W1121 16:55:17.768302 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.84
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.85
W1121 16:55:17.768397 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.85
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.86
W1121 16:55:17.768491 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.86
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.87
W1121 16:55:17.768585 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.87
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.88
W1121 16:55:17.768680 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.88
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.89
W1121 16:55:17.768774 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.89
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.90
W1121 16:55:17.768869 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.90
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.91
W1121 16:55:17.768963 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.91
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.92
W1121 16:55:17.769058 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.92
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.93
W1121 16:55:17.769152 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.93
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.94
W1121 16:55:17.769246 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.94
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.95
W1121 16:55:17.769340 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.95
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.96
W1121 16:55:17.769435 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.96
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.97
W1121 16:55:17.769530 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.97
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.98
W1121 16:55:17.769624 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.98
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.99
W1121 16:55:17.769718 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.99
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.100
W1121 16:55:17.769812 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.100
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.101
W1121 16:55:17.769905 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.101
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.102
W1121 16:55:17.770000 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.102
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.103
W1121 16:55:17.770094 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.103
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.104
W1121 16:55:17.770188 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.104
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.105
W1121 16:55:17.770286 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.105
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.106
W1121 16:55:17.770380 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.106
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.107
W1121 16:55:17.770475 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.107
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.108
W1121 16:55:17.770570 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.108
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.109
W1121 16:55:17.770664 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.109
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.110
W1121 16:55:17.770761 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.110
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.111
W1121 16:55:17.770856 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.111
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.112
W1121 16:55:17.770950 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.112
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.113
W1121 16:55:17.771044 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.113
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.114
W1121 16:55:17.771138 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.114
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.115
W1121 16:55:17.771234 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.115
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.116
W1121 16:55:17.771330 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.116
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.117
W1121 16:55:17.771425 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.117
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.118
W1121 16:55:17.771519 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.118
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.119
W1121 16:55:17.771613 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.119
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.120
W1121 16:55:17.771708 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.120
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.121
W1121 16:55:17.771806 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.121
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.122
W1121 16:55:17.771900 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.122
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.123
W1121 16:55:17.771994 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.123
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.124
W1121 16:55:17.772089 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.124
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.125
W1121 16:55:17.772183 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.125
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.126
W1121 16:55:17.772276 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.126
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.127
W1121 16:55:17.772370 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.127
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.128
W1121 16:55:17.772465 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.128
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.129
W1121 16:55:17.772560 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.129
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.130
W1121 16:55:17.772655 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.131
W1121 16:55:17.772750 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.132
W1121 16:55:17.772844 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.133
W1121 16:55:17.772938 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.134
W1121 16:55:17.773031 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.135
W1121 16:55:17.773125 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.136
W1121 16:55:17.773218 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.137
W1121 16:55:17.773312 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.138
W1121 16:55:17.773406 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.139
W1121 16:55:17.773500 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.140
W1121 16:55:17.773594 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.141
W1121 16:55:17.773688 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.142
W1121 16:55:17.773781 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.143
W1121 16:55:17.773875 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.144
W1121 16:55:17.773969 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.145
W1121 16:55:17.774064 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.146
W1121 16:55:17.774159 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.147
W1121 16:55:17.774253 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.148
W1121 16:55:17.774360 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.149
W1121 16:55:17.774456 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.150
W1121 16:55:17.774551 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.151
W1121 16:55:17.774646 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.152
W1121 16:55:17.774740 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.153
W1121 16:55:17.774834 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.154
W1121 16:55:17.774928 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.155
W1121 16:55:17.775023 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.156
W1121 16:55:17.775116 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.157
W1121 16:55:17.775211 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.158
W1121 16:55:17.775305 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.159
W1121 16:55:17.775400 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.160
W1121 16:55:17.775494 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.161
W1121 16:55:17.775589 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.162
W1121 16:55:17.775697 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.163
W1121 16:55:17.775812 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.164
W1121 16:55:17.775909 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.165
W1121 16:55:17.776003 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.166
W1121 16:55:17.776098 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.167
W1121 16:55:17.776193 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.168
W1121 16:55:17.776287 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.169
W1121 16:55:17.776382 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.170
W1121 16:55:17.776476 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.171
W1121 16:55:17.776570 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.172
W1121 16:55:17.776664 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.173
W1121 16:55:17.776757 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.174
W1121 16:55:17.776851 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.175
W1121 16:55:17.776947 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.176
W1121 16:55:17.777041 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.177
W1121 16:55:17.777136 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.178
W1121 16:55:17.777231 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.179
W1121 16:55:17.777325 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.180
W1121 16:55:17.777419 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.181
W1121 16:55:17.777514 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.182
W1121 16:55:17.777608 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.183
W1121 16:55:17.777702 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.184
W1121 16:55:17.777797 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.185
W1121 16:55:17.777892 139767974977920 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.185
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 91, in test_train_eval
    self._restore_evaluate('/home/jmw/ing/myfi/vfi/ckpt/ckpt-0')
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 64, in _restore_evaluate
    _, metrics = test_step(img0,gt,img1,0.5)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 915, in __call__
    result = self._call(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 980, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2496, in __call__
    return graph_function._call_flat(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1862, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 499, in call
    outputs = execute.execute(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:
Detected at node 'conv_block_3/sequential_25/p_re_lu_26/mul' defined at (most recent call last):
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 107, in <module>
      tf.test.main()
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/test.py", line 56, in main
      return _googletest.main(argv)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 62, in main
      benchmark.benchmarks_main(true_main=main_wrapper, argv=argv)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 60, in main_wrapper
      return app.run(main=g_main, argv=args)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/app.py", line 308, in run
      _run_main(main, args)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
      sys.exit(main(argv))
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 51, in g_main
      absltest_main(argv=argv)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2051, in main
      _run_in_app(run_tests, args, kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2146, in _run_in_app
      function(argv, args, kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2549, in run_tests
      result = _run_and_get_tests_result(
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2518, in _run_and_get_tests_result
      test_program = unittest.TestProgram(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/main.py", line 101, in __init__
      self.runTests()
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/main.py", line 271, in runTests
      self.result = testRunner.run(self.test)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/_pretty_print_reporter.py", line 82, in run
      return super(TextTestRunner, self).run(test)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/runner.py", line 184, in run
      test(result)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 84, in __call__
      return self.run(*args, **kwds)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 122, in run
      test(result)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 84, in __call__
      return self.run(*args, **kwds)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 122, in run
      test(result)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 651, in __call__
      return self.run(*args, **kwds)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 592, in run
      self._callTestMethod(testMethod)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
      method()
    File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 91, in test_train_eval
      self._restore_evaluate('/home/jmw/ing/myfi/vfi/ckpt/ckpt-0')
    File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 64, in _restore_evaluate
      _, metrics = test_step(img0,gt,img1,0.5)
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 299, in interpolator
      af, mf  = self.feature_estimation(img0, img1) # feature extractor [[2,256,30,60],,...]5개, [[2,256,30,60],...] 3개
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 125, in __call__
      for i in range(self.num_stages): # 5,  i 0,1,2,3,4
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 133, in __call__
      if i < self.conv_stages: #i < 3
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 136, in __call__
      x = block(x)  # C C C
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/ing/myfi/vfi/src/modules.py", line 421, in call
      x = self.layers(x)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/sequential.py", line 410, in call
      return super().call(inputs, training=training, mask=mask)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 61, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/keras/layers/activation/prelu.py", line 109, in call
      neg = -self.alpha * backend.relu(-inputs)
Node: 'conv_block_3/sequential_25/p_re_lu_26/mul'
required broadcastable shapes
	 [[{{node conv_block_3/sequential_25/p_re_lu_26/mul}}]] [Op:__inference_interpolator_8639]
----------------------------------------------------------------------
Ran 2 tests in 8.580s
FAILED (errors=1, skipped=1)