Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
































































































 13%|███████████                                                                             | 101/802 [03:43<25:51,  2.21s/batch, epoch=0, loss=44.7, mse=2.88e+4, psnr=3.9]
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 102, in <module>
    tf.test.main()
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/test.py", line 56, in main
    return _googletest.main(argv)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 62, in main
    benchmark.benchmarks_main(true_main=main_wrapper, argv=argv)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/benchmark.py", line 503, in benchmarks_main
    true_main()
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 60, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/platform/googletest.py", line 51, in g_main
    absltest_main(argv=argv)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2051, in main
    _run_in_app(run_tests, args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2146, in _run_in_app
    function(argv, args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2549, in run_tests
    result = _run_and_get_tests_result(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/absltest.py", line 2518, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/absl/testing/_pretty_print_reporter.py", line 82, in run
    return super(TextTestRunner, self).run(test)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/runner.py", line 184, in run
    test(result)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 92, in test_train_eval
    tepoch.set_postfix(epoch=epoch,psnr=metrics['psnr'].numpy() , loss =metrics['loss'].numpy() ,mse =metrics['mse'].numpy()  )
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1157, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1123, in _numpy
    return self._numpy_internal()
KeyboardInterrupt