Traceback (most recent call last):
  File "/home/lab-com/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lab-com/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jmw/backup/FILM/vfi/src/train.py", line 37, in <module>
    model= models.Model(config)
  File "/home/jmw/backup/FILM/vfi/src/models.py", line 52, in __init__
    self.extract = feature_extractor.feature_extractor('feat_net', self.config)
AttributeError: module 'vfi.src.feature_extractor' has no attribute 'feature_extractor'