Running tests under Python 3.9.18: /home/jmw/anaconda3/envs/vct_tf/bin/python
[ RUN      ] ModelsTest.test_session
[  SKIPPED ] ModelsTest.test_session
[ RUN      ] ModelsTest.test_train_eval
  0%|                                                                                                                                                                                  | 0/802 [00:00<?, ?batch/s]
resume /home/jmw/ing/myfi/vfi/ckpt
  0%|                                                                                                                                                                                  | 0/802 [00:02<?, ?batch/s]
INFO:tensorflow:time(__main__.ModelsTest.test_train_eval): 3.52s
I1121 18:26:01.732819 139857428173184 test_util.py:2460] time(__main__.ModelsTest.test_train_eval): 3.52s
[  FAILED  ] ModelsTest.test_train_eval
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
W1121 18:26:01.737828 139857428173184 checkpoint.py:204] Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.iter
W1121 18:26:01.738032 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_1
W1121 18:26:01.738211 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_2
W1121 18:26:01.738447 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer.decay
W1121 18:26:01.738703 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.130
W1121 18:26:01.738842 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.131
W1121 18:26:01.738971 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.132
W1121 18:26:01.739166 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.133
W1121 18:26:01.739349 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.134
W1121 18:26:01.739478 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.135
W1121 18:26:01.739605 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.136
W1121 18:26:01.739732 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.137
W1121 18:26:01.739911 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.138
W1121 18:26:01.740067 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.139
W1121 18:26:01.740243 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.140
W1121 18:26:01.740371 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.141
W1121 18:26:01.740497 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.142
W1121 18:26:01.740624 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.143
W1121 18:26:01.740747 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.144
W1121 18:26:01.740875 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.145
W1121 18:26:01.740999 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.146
W1121 18:26:01.741122 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.147
W1121 18:26:01.741247 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.148
W1121 18:26:01.741373 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.149
W1121 18:26:01.741498 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.150
W1121 18:26:01.741623 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.151
W1121 18:26:01.741748 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.152
W1121 18:26:01.741872 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.153
W1121 18:26:01.741997 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.154
W1121 18:26:01.742121 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.155
W1121 18:26:01.742245 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.156
W1121 18:26:01.742390 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.157
W1121 18:26:01.742537 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.158
W1121 18:26:01.742666 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.159
W1121 18:26:01.742791 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.160
W1121 18:26:01.742918 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.161
W1121 18:26:01.743042 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.162
W1121 18:26:01.743168 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.163
W1121 18:26:01.743297 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.164
W1121 18:26:01.743443 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.165
W1121 18:26:01.743584 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.166
W1121 18:26:01.743722 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.167
W1121 18:26:01.743851 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.168
W1121 18:26:01.743993 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.169
W1121 18:26:01.744151 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.170
W1121 18:26:01.744310 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.171
W1121 18:26:01.744444 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.172
W1121 18:26:01.744568 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.173
W1121 18:26:01.744692 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.174
W1121 18:26:01.744814 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.175
W1121 18:26:01.744936 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.176
W1121 18:26:01.745058 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.177
W1121 18:26:01.745181 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.178
W1121 18:26:01.745303 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.179
W1121 18:26:01.745424 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.180
W1121 18:26:01.745546 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.181
W1121 18:26:01.745668 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.182
W1121 18:26:01.745790 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.183
W1121 18:26:01.745912 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.184
W1121 18:26:01.746033 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.185
W1121 18:26:01.746155 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._all_trainable_variables.185
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.0
W1121 18:26:01.746281 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.0
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.1
W1121 18:26:01.746405 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.2
W1121 18:26:01.746528 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.3
W1121 18:26:01.746651 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.3
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.4
W1121 18:26:01.746775 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.4
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.5
W1121 18:26:01.746897 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.5
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.6
W1121 18:26:01.747020 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.6
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.7
W1121 18:26:01.747202 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.7
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.8
W1121 18:26:01.747391 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.8
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.9
W1121 18:26:01.747547 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.9
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.10
W1121 18:26:01.747697 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.10
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.11
W1121 18:26:01.747831 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.11
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.12
W1121 18:26:01.747955 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.12
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.13
W1121 18:26:01.748079 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.13
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.14
W1121 18:26:01.748202 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.14
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.15
W1121 18:26:01.748328 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.15
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.16
W1121 18:26:01.748470 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.16
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.17
W1121 18:26:01.748609 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.17
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.18
W1121 18:26:01.748749 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.18
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.19
W1121 18:26:01.748938 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.19
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.20
W1121 18:26:01.749155 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.20
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.21
W1121 18:26:01.749294 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.21
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.22
W1121 18:26:01.749484 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.22
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.23
W1121 18:26:01.749607 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.23
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.24
W1121 18:26:01.749728 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.24
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.25
W1121 18:26:01.749850 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.25
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.26
W1121 18:26:01.749973 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.26
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.27
W1121 18:26:01.750097 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.27
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.28
W1121 18:26:01.750218 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.28
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.29
W1121 18:26:01.750381 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.29
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.30
W1121 18:26:01.750505 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.30
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.31
W1121 18:26:01.750628 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.31
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.32
W1121 18:26:01.750750 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.32
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.33
W1121 18:26:01.750873 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.33
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.34
W1121 18:26:01.750996 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.34
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.35
W1121 18:26:01.751118 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.35
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.36
W1121 18:26:01.751242 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.36
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.37
W1121 18:26:01.751364 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.37
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.38
W1121 18:26:01.751487 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.38
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.39
W1121 18:26:01.751608 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.39
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.40
W1121 18:26:01.751736 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.40
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.41
W1121 18:26:01.751857 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.41
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.42
W1121 18:26:01.751978 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.42
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.43
W1121 18:26:01.752118 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.43
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.44
W1121 18:26:01.752255 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.44
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.45
W1121 18:26:01.752412 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.45
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.46
W1121 18:26:01.752569 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.46
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.47
W1121 18:26:01.752707 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.47
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.48
W1121 18:26:01.752870 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.48
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.49
W1121 18:26:01.753015 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.49
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.50
W1121 18:26:01.753147 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.50
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.51
W1121 18:26:01.753271 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.51
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.52
W1121 18:26:01.753419 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.52
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.53
W1121 18:26:01.753562 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.53
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.54
W1121 18:26:01.753704 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.54
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.55
W1121 18:26:01.753835 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.55
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.56
W1121 18:26:01.753962 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.56
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.57
W1121 18:26:01.754087 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.57
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.58
W1121 18:26:01.754211 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.58
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.59
W1121 18:26:01.754354 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.59
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.60
W1121 18:26:01.754477 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.60
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.61
W1121 18:26:01.754632 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.61
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.62
W1121 18:26:01.754753 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.62
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.63
W1121 18:26:01.754873 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.63
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.64
W1121 18:26:01.754995 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.64
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.65
W1121 18:26:01.755115 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.65
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.66
W1121 18:26:01.755238 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.66
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.67
W1121 18:26:01.755361 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.67
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.68
W1121 18:26:01.755484 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.68
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.69
W1121 18:26:01.755607 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.69
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.70
W1121 18:26:01.755730 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.70
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.71
W1121 18:26:01.755852 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.71
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.72
W1121 18:26:01.756003 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.72
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.73
W1121 18:26:01.756126 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.73
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.74
W1121 18:26:01.756247 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.74
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.75
W1121 18:26:01.756370 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.75
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.76
W1121 18:26:01.756492 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.76
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.77
W1121 18:26:01.756615 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.77
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.78
W1121 18:26:01.756736 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.78
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.79
W1121 18:26:01.756886 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.79
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.80
W1121 18:26:01.757008 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.80
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.81
W1121 18:26:01.757130 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.81
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.82
W1121 18:26:01.757252 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.82
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.83
W1121 18:26:01.757394 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.83
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.84
W1121 18:26:01.757557 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.84
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.85
W1121 18:26:01.757685 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.85
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.86
W1121 18:26:01.757842 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.86
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.87
W1121 18:26:01.757972 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.87
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.88
W1121 18:26:01.758097 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.88
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.89
W1121 18:26:01.758222 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.89
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.90
W1121 18:26:01.758377 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.90
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.91
W1121 18:26:01.758517 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.91
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.92
W1121 18:26:01.758655 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.92
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.93
W1121 18:26:01.758830 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.93
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.94
W1121 18:26:01.758955 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.94
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.95
W1121 18:26:01.759131 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.95
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.96
W1121 18:26:01.759314 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.96
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.97
W1121 18:26:01.759465 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.97
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.98
W1121 18:26:01.759662 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.98
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.99
W1121 18:26:01.759782 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.99
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.100
W1121 18:26:01.759902 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.100
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.101
W1121 18:26:01.760040 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.101
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.102
W1121 18:26:01.760162 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.102
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.103
W1121 18:26:01.760284 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.103
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.104
W1121 18:26:01.760433 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.104
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.105
W1121 18:26:01.760566 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.105
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.106
W1121 18:26:01.760702 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.106
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.107
W1121 18:26:01.760824 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.107
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.108
W1121 18:26:01.760977 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.108
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.109
W1121 18:26:01.761096 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.109
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.110
W1121 18:26:01.761238 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.110
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.111
W1121 18:26:01.761359 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.111
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.112
W1121 18:26:01.761484 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.112
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.113
W1121 18:26:01.761603 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.113
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.114
W1121 18:26:01.761725 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.114
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.115
W1121 18:26:01.761847 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.115
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.116
W1121 18:26:01.761977 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.116
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.117
W1121 18:26:01.762109 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.117
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.118
W1121 18:26:01.762242 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.118
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.119
W1121 18:26:01.762416 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.119
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.120
W1121 18:26:01.762563 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.120
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.121
W1121 18:26:01.762697 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.121
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.122
W1121 18:26:01.762828 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.122
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.123
W1121 18:26:01.762959 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.123
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.124
W1121 18:26:01.763090 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.124
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.125
W1121 18:26:01.763221 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.125
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.126
W1121 18:26:01.763434 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.126
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.127
W1121 18:26:01.763586 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.127
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.128
W1121 18:26:01.763770 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.128
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.129
W1121 18:26:01.763972 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.129
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.130
W1121 18:26:01.764186 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.131
W1121 18:26:01.764317 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.132
W1121 18:26:01.764447 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.133
W1121 18:26:01.764578 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.134
W1121 18:26:01.764707 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.135
W1121 18:26:01.764838 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.136
W1121 18:26:01.764989 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.137
W1121 18:26:01.765125 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.138
W1121 18:26:01.765297 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.139
W1121 18:26:01.765439 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.140
W1121 18:26:01.765566 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.141
W1121 18:26:01.765693 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.142
W1121 18:26:01.765819 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.143
W1121 18:26:01.765944 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.144
W1121 18:26:01.766068 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.145
W1121 18:26:01.766193 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.146
W1121 18:26:01.766323 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.147
W1121 18:26:01.766445 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.148
W1121 18:26:01.766569 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.149
W1121 18:26:01.766695 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.150
W1121 18:26:01.766836 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.151
W1121 18:26:01.767000 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.152
W1121 18:26:01.767127 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.153
W1121 18:26:01.767255 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.154
W1121 18:26:01.767400 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.155
W1121 18:26:01.767544 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.156
W1121 18:26:01.767671 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.157
W1121 18:26:01.767797 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.158
W1121 18:26:01.767920 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.159
W1121 18:26:01.768044 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.160
W1121 18:26:01.768170 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.161
W1121 18:26:01.768299 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.162
W1121 18:26:01.768443 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.163
W1121 18:26:01.768584 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.164
W1121 18:26:01.768734 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.165
W1121 18:26:01.768902 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.166
W1121 18:26:01.769066 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.167
W1121 18:26:01.769203 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.168
W1121 18:26:01.769330 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.169
W1121 18:26:01.769453 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.170
W1121 18:26:01.769577 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.171
W1121 18:26:01.769703 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.172
W1121 18:26:01.769829 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.173
W1121 18:26:01.769955 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.174
W1121 18:26:01.770080 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.175
W1121 18:26:01.770205 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.176
W1121 18:26:01.770369 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.177
W1121 18:26:01.770511 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.178
W1121 18:26:01.770653 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.179
W1121 18:26:01.770779 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.180
W1121 18:26:01.770903 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.181
W1121 18:26:01.771027 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.182
W1121 18:26:01.771165 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.183
W1121 18:26:01.771285 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.184
W1121 18:26:01.771407 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.185
W1121 18:26:01.771551 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'm' for (root).model._all_trainable_variables.185
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.0
W1121 18:26:01.771677 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.0
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.1
W1121 18:26:01.771899 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.2
W1121 18:26:01.772072 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.3
W1121 18:26:01.772246 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.3
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.4
W1121 18:26:01.772382 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.4
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.5
W1121 18:26:01.772526 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.5
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.6
W1121 18:26:01.772652 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.6
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.7
W1121 18:26:01.772776 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.7
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.8
W1121 18:26:01.772908 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.8
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.9
W1121 18:26:01.773041 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.9
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.10
W1121 18:26:01.773173 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.10
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.11
W1121 18:26:01.773308 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.11
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.12
W1121 18:26:01.773463 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.12
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.13
W1121 18:26:01.773616 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.13
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.14
W1121 18:26:01.773768 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.14
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.15
W1121 18:26:01.773903 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.15
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.16
W1121 18:26:01.774035 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.16
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.17
W1121 18:26:01.774168 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.17
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.18
W1121 18:26:01.774307 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.18
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.19
W1121 18:26:01.774440 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.19
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.20
W1121 18:26:01.774573 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.20
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.21
W1121 18:26:01.774706 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.21
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.22
W1121 18:26:01.774837 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.22
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.23
W1121 18:26:01.774971 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.23
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.24
W1121 18:26:01.775101 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.24
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.25
W1121 18:26:01.775235 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.25
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.26
W1121 18:26:01.775367 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.26
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.27
W1121 18:26:01.775497 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.27
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.28
W1121 18:26:01.775631 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.28
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.29
W1121 18:26:01.775762 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.29
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.30
W1121 18:26:01.775892 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.30
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.31
W1121 18:26:01.776016 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.31
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.32
W1121 18:26:01.776141 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.32
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.33
W1121 18:26:01.776289 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.33
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.34
W1121 18:26:01.776433 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.34
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.35
W1121 18:26:01.776566 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.35
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.36
W1121 18:26:01.776703 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.36
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.37
W1121 18:26:01.776828 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.37
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.38
W1121 18:26:01.776952 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.38
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.39
W1121 18:26:01.777075 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.39
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.40
W1121 18:26:01.777199 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.40
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.41
W1121 18:26:01.777329 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.41
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.42
W1121 18:26:01.777479 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.42
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.43
W1121 18:26:01.777612 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.43
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.44
W1121 18:26:01.777734 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.44
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.45
W1121 18:26:01.777860 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.45
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.46
W1121 18:26:01.777986 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.46
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.47
W1121 18:26:01.778108 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.47
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.48
W1121 18:26:01.778233 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.48
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.49
W1121 18:26:01.778378 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.49
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.50
W1121 18:26:01.778520 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.50
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.51
W1121 18:26:01.778661 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.51
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.52
W1121 18:26:01.778796 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.52
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.53
W1121 18:26:01.778922 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.53
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.54
W1121 18:26:01.779046 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.54
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.55
W1121 18:26:01.779170 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.55
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.56
W1121 18:26:01.779290 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.56
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.57
W1121 18:26:01.779413 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.57
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.58
W1121 18:26:01.779537 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.58
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.59
W1121 18:26:01.779659 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.59
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.60
W1121 18:26:01.779784 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.60
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.61
W1121 18:26:01.779908 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.61
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.62
W1121 18:26:01.780033 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.62
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.63
W1121 18:26:01.780163 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.63
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.64
W1121 18:26:01.780326 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.64
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.65
W1121 18:26:01.780456 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.65
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.66
W1121 18:26:01.780582 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.66
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.67
W1121 18:26:01.780707 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.67
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.68
W1121 18:26:01.780832 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.68
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.69
W1121 18:26:01.780957 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.69
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.70
W1121 18:26:01.781082 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.70
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.71
W1121 18:26:01.781206 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.71
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.72
W1121 18:26:01.781330 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.72
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.73
W1121 18:26:01.781455 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.73
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.74
W1121 18:26:01.781580 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.74
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.75
W1121 18:26:01.781705 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.75
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.76
W1121 18:26:01.781829 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.76
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.77
W1121 18:26:01.781951 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.77
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.78
W1121 18:26:01.782074 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.78
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.79
W1121 18:26:01.782197 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.79
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.80
W1121 18:26:01.782330 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.80
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.81
W1121 18:26:01.782483 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.81
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.82
W1121 18:26:01.782616 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.82
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.83
W1121 18:26:01.782742 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.83
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.84
W1121 18:26:01.782866 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.84
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.85
W1121 18:26:01.782990 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.85
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.86
W1121 18:26:01.783114 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.86
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.87
W1121 18:26:01.783238 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.87
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.88
W1121 18:26:01.783376 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.88
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.89
W1121 18:26:01.783517 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.89
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.90
W1121 18:26:01.783658 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.90
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.91
W1121 18:26:01.783800 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.91
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.92
W1121 18:26:01.783926 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.92
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.93
W1121 18:26:01.784049 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.93
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.94
W1121 18:26:01.784173 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.94
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.95
W1121 18:26:01.784297 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.95
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.96
W1121 18:26:01.784420 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.96
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.97
W1121 18:26:01.784543 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.97
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.98
W1121 18:26:01.784666 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.98
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.99
W1121 18:26:01.784790 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.99
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.100
W1121 18:26:01.784914 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.100
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.101
W1121 18:26:01.785036 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.101
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.102
W1121 18:26:01.785159 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.102
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.103
W1121 18:26:01.785285 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.103
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.104
W1121 18:26:01.785409 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.104
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.105
W1121 18:26:01.785533 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.105
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.106
W1121 18:26:01.785655 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.106
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.107
W1121 18:26:01.785780 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.107
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.108
W1121 18:26:01.785903 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.108
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.109
W1121 18:26:01.786028 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.109
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.110
W1121 18:26:01.786152 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.110
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.111
W1121 18:26:01.786280 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.111
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.112
W1121 18:26:01.786405 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.112
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.113
W1121 18:26:01.786529 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.113
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.114
W1121 18:26:01.786653 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.114
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.115
W1121 18:26:01.786777 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.115
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.116
W1121 18:26:01.786901 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.116
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.117
W1121 18:26:01.787026 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.117
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.118
W1121 18:26:01.787150 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.118
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.119
W1121 18:26:01.787274 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.119
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.120
W1121 18:26:01.787418 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.120
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.121
W1121 18:26:01.787573 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.121
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.122
W1121 18:26:01.787736 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.122
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.123
W1121 18:26:01.787897 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.123
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.124
W1121 18:26:01.788035 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.124
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.125
W1121 18:26:01.788177 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.125
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.126
W1121 18:26:01.788322 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.126
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.127
W1121 18:26:01.788483 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.127
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.128
W1121 18:26:01.788642 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.128
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.129
W1121 18:26:01.788801 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.129
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.130
W1121 18:26:01.788937 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.130
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.131
W1121 18:26:01.789073 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.131
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.132
W1121 18:26:01.789209 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.132
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.133
W1121 18:26:01.789342 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.133
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.134
W1121 18:26:01.789477 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.134
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.135
W1121 18:26:01.789610 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.135
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.136
W1121 18:26:01.789738 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.136
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.137
W1121 18:26:01.789861 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.137
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.138
W1121 18:26:01.789983 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.138
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.139
W1121 18:26:01.790104 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.139
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.140
W1121 18:26:01.790225 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.140
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.141
W1121 18:26:01.790355 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.141
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.142
W1121 18:26:01.790482 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.142
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.143
W1121 18:26:01.790608 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.143
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.144
W1121 18:26:01.790733 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.144
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.145
W1121 18:26:01.790858 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.145
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.146
W1121 18:26:01.790981 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.146
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.147
W1121 18:26:01.791105 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.147
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.148
W1121 18:26:01.791229 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.148
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.149
W1121 18:26:01.791352 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.149
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.150
W1121 18:26:01.791473 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.150
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.151
W1121 18:26:01.791595 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.151
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.152
W1121 18:26:01.791755 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.152
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.153
W1121 18:26:01.791901 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.153
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.154
W1121 18:26:01.792029 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.154
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.155
W1121 18:26:01.792154 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.155
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.156
W1121 18:26:01.792285 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.156
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.157
W1121 18:26:01.792437 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.157
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.158
W1121 18:26:01.792565 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.158
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.159
W1121 18:26:01.792692 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.159
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.160
W1121 18:26:01.792819 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.160
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.161
W1121 18:26:01.792944 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.161
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.162
W1121 18:26:01.793068 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.162
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.163
W1121 18:26:01.793193 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.163
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.164
W1121 18:26:01.793312 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.164
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.165
W1121 18:26:01.793456 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.165
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.166
W1121 18:26:01.793597 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.166
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.167
W1121 18:26:01.793738 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.167
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.168
W1121 18:26:01.793865 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.168
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.169
W1121 18:26:01.793987 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.169
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.170
W1121 18:26:01.794124 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.170
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.171
W1121 18:26:01.794247 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.171
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.172
W1121 18:26:01.794381 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.172
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.173
W1121 18:26:01.794504 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.173
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.174
W1121 18:26:01.794628 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.174
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.175
W1121 18:26:01.794761 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.175
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.176
W1121 18:26:01.794897 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.176
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.177
W1121 18:26:01.795030 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.177
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.178
W1121 18:26:01.795198 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.178
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.179
W1121 18:26:01.795350 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.179
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.180
W1121 18:26:01.795485 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.180
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.181
W1121 18:26:01.795617 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.181
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.182
W1121 18:26:01.795749 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.182
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.183
W1121 18:26:01.795881 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.183
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.184
W1121 18:26:01.796013 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.184
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.185
W1121 18:26:01.796145 139857428173184 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model.optimizer's state 'v' for (root).model._all_trainable_variables.185
======================================================================
ERROR: test_train_eval (__main__.ModelsTest)
ModelsTest.test_train_eval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmw/ing/myfi/vfi/src/models_test.py", line 95, in test_train_eval
    metrics=train_step(img0,gt,img1)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 915, in __call__
    result = self._call(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 963, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2523, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2760, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2670, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1247, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1233, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1222, in autograph_handler
    return autograph.converted_call(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filenfuimav4.py", line 11, in tf__train_step
    (pred, metric) = ag__.converted_call(ag__.ld(self).interpolator, (ag__.ld(img0), ag__.ld(gt), ag__.ld(img1)), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_file6ppr05xg.py", line 64, in tf__interpolator
    ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(self).flow_num_stage,), None, fscope), None, loop_body, get_state_1, set_state_1, ('flow', 'mask', 'warped_img0', 'warped_img1'), {'iterate_names': 'i'})
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 463, in for_stmt
    _py_for_stmt(iter_, extra_test, body, None, None)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 512, in _py_for_stmt
    body(target)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 478, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_file6ppr05xg.py", line 51, in loop_body
    ag__.if_stmt(ag__.ld(flow) != None, if_body, else_body, get_state, set_state, ('flow', 'mask'), 2)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1363, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1416, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_file6ppr05xg.py", line 50, in else_body
    (flow, mask) = ag__.converted_call(ag__.ld(self).block[ag__.ld(i)], (), dict(motion_feature=ag__.ld(m), x=ag__.ld(x2), flow=None), fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileb9amvxjt.py", line 61, in tf____call__
    x = ag__.converted_call(ag__.ld(self).conv, (ag__.converted_call(ag__.ld(tf).concat, ([ag__.ld(motion_feature), ag__.ld(x)], -1), None, fscope),), None, fscope)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 1823, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1276, in concat_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 735, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3800, in _create_op_internal
    ret = Operation(
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2108, in __init__
    c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1969, in _create_c_op
    raise ValueError(e.message)
ValueError: in user code:
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 260, in train_step  *
        pred,metric = self.interpolator(img0,gt,img1)
    File "/home/jmw/ing/myfi/vfi/src/model.py", line 321, in interpolator  *
        flow, mask = self.block[i](
    File "/home/jmw/ing/myfi/vfi/src/modules.py", line 534, in __call__  *
        x = self.conv(tf.concat([motion_feature, x], -1))    #64+6, 32+17
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler  **
        return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
        return dispatch_target(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 1823, in concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1276, in concat_v2
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 735, in _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3800, in _create_op_internal
        ret = Operation(
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2108, in __init__
        c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
        return fn(*args, **kwargs)
    File "/home/jmw/anaconda3/envs/vct_tf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1969, in _create_c_op
        raise ValueError(e.message)
    ValueError: Dimension 1 in both shapes must be equal, but are 1024 and 64. Shapes are [64,1024,1024] and [64,64,64]. for '{{node concat_5}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](resize/ResizeBilinear, resize_1/ResizeBilinear, concat_5/axis)' with input shapes: [64,1024,1024,1024], [64,64,64,6], [] and with computed input tensors: input[2] = <-1>.
----------------------------------------------------------------------
Ran 2 tests in 3.579s
FAILED (errors=1, skipped=1)